name: "\U0001F41E Bug report"
description: Create a report to help improving the project

body:
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
     required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description:
        Steps to reproduce the behavior. Contributors should be able to follow the steps provided in order to reproduce. Screenshots and / or screencasts can help to understand the problem.
        the bug.
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional information
      description: If applicable, add any other information abour the problem and your environment here
